!initialize all parameters=====================================================
subroutine init(ni, nj, nk, u, v, w, un, vn, wn, rho, mu, rhon, mun, &
                adv_u, adv_v, adv_w, adv_uo, adv_vo, adv_wo, &
                prs_u, prs_v, prs_w, s, tau, vis_u, vis_v, vis_w, &
                sum_fst_u, sum_fst_v, sum_fst_w, &
                sum_fst_un, sum_fst_vn, sum_fst_wn, src_u, src_v, src_w, &
                au_w_u, au_e_u, au_s_u, au_n_u, au_b_u, au_t_u, au_p_u, &
                av_ws_u, av_es_u, av_wn_u, av_en_u, &
                aw_wb_u, aw_eb_u, aw_wt_u, aw_et_u, &
                av_w_v, av_e_v, av_s_v, av_n_v, av_b_v, av_t_v, av_p_v, &
                au_sw_v, au_nw_v, au_se_v, au_ne_v, &
                aw_sb_v, aw_nb_v, aw_st_v, aw_nt_v, &
                aw_w_w, aw_e_w, aw_s_w, aw_n_w, aw_b_w, aw_t_w, aw_p_w, &
                au_bw_w, au_tw_w, au_be_w, au_te_w, &
                av_bs_w, av_ts_w, av_bn_w, av_tn_w, &
                rhol, mul)
        implicit none
  integer :: ni, nj, nk
  real(8) ::          u(-2:ni+3, -2:nj+3, -2:nk+3)
  real(8) ::          v(-2:ni+3, -2:nj+3, -2:nk+3)
  real(8) ::          w(-2:ni+3, -2:nj+3, -2:nk+3)
  real(8) ::         un(-2:ni+3, -2:nj+3, -2:nk+3)
  real(8) ::         vn(-2:ni+3, -2:nj+3, -2:nk+3)
  real(8) ::         wn(-2:ni+3, -2:nj+3, -2:nk+3)
  real(8) ::        rho(-2:ni+3, -2:nj+3, -2:nk+3)
  real(8) ::         mu(-2:ni+3, -2:nj+3, -2:nk+3)
  real(8) ::       rhon(-2:ni+3, -2:nj+3, -2:nk+3)
  real(8) ::        mun(-2:ni+3, -2:nj+3, -2:nk+3)

  real(8) ::      adv_u(-2:ni+3, -2:nj+3, -2:nk+3)
  real(8) ::      adv_v(-2:ni+3, -2:nj+3, -2:nk+3)
  real(8) ::      adv_w(-2:ni+3, -2:nj+3, -2:nk+3)
  real(8) ::     adv_uo(-2:ni+3, -2:nj+3, -2:nk+3)
  real(8) ::     adv_vo(-2:ni+3, -2:nj+3, -2:nk+3)
  real(8) ::     adv_wo(-2:ni+3, -2:nj+3, -2:nk+3)

  real(8) ::      prs_u(-2:ni+3, -2:nj+3, -2:nk+3)
  real(8) ::      prs_v(-2:ni+3, -2:nj+3, -2:nk+3)
  real(8) ::      prs_w(-2:ni+3, -2:nj+3, -2:nk+3)

  real(8) ::          s(-2:ni+3, -2:nj+3, -2:nk+3, 6)
  real(8) ::        tau(-2:ni+3, -2:nj+3, -2:nk+3, 6)
  real(8) ::      vis_u(-2:ni+3, -2:nj+3, -2:nk+3)
  real(8) ::      vis_v(-2:ni+3, -2:nj+3, -2:nk+3)
  real(8) ::      vis_w(-2:ni+3, -2:nj+3, -2:nk+3)

  real(8) ::  sum_fst_u(-2:ni+3, -2:nj+3, -2:nk+3)
  real(8) ::  sum_fst_v(-2:ni+3, -2:nj+3, -2:nk+3)
  real(8) ::  sum_fst_w(-2:ni+3, -2:nj+3, -2:nk+3)
  real(8) :: sum_fst_un(-2:ni+3, -2:nj+3, -2:nk+3)
  real(8) :: sum_fst_vn(-2:ni+3, -2:nj+3, -2:nk+3)
  real(8) :: sum_fst_wn(-2:ni+3, -2:nj+3, -2:nk+3)
  
  real(8) ::      src_u(-2:ni+3, -2:nj+3, -2:nk+3)
  real(8) ::      src_v(-2:ni+3, -2:nj+3, -2:nk+3)
  real(8) ::      src_w(-2:ni+3, -2:nj+3, -2:nk+3)

  real(8) ::     au_w_u(-2:ni+3, -2:nj+3, -2:nk+3)
  real(8) ::     au_e_u(-2:ni+3, -2:nj+3, -2:nk+3)
  real(8) ::     au_s_u(-2:ni+3, -2:nj+3, -2:nk+3)
  real(8) ::     au_n_u(-2:ni+3, -2:nj+3, -2:nk+3)
  real(8) ::     au_b_u(-2:ni+3, -2:nj+3, -2:nk+3)
  real(8) ::     au_t_u(-2:ni+3, -2:nj+3, -2:nk+3)
  real(8) ::     au_p_u(-2:ni+3, -2:nj+3, -2:nk+3)
  real(8) ::    av_ws_u(-2:ni+3, -2:nj+3, -2:nk+3)
  real(8) ::    av_es_u(-2:ni+3, -2:nj+3, -2:nk+3)
  real(8) ::    av_wn_u(-2:ni+3, -2:nj+3, -2:nk+3)
  real(8) ::    av_en_u(-2:ni+3, -2:nj+3, -2:nk+3)
  real(8) ::    aw_wb_u(-2:ni+3, -2:nj+3, -2:nk+3)
  real(8) ::    aw_eb_u(-2:ni+3, -2:nj+3, -2:nk+3)
  real(8) ::    aw_wt_u(-2:ni+3, -2:nj+3, -2:nk+3)
  real(8) ::    aw_et_u(-2:ni+3, -2:nj+3, -2:nk+3)
  real(8) ::     av_w_v(-2:ni+3, -2:nj+3, -2:nk+3)
  real(8) ::     av_e_v(-2:ni+3, -2:nj+3, -2:nk+3)
  real(8) ::     av_s_v(-2:ni+3, -2:nj+3, -2:nk+3)
  real(8) ::     av_n_v(-2:ni+3, -2:nj+3, -2:nk+3)
  real(8) ::     av_b_v(-2:ni+3, -2:nj+3, -2:nk+3)
  real(8) ::     av_t_v(-2:ni+3, -2:nj+3, -2:nk+3)
  real(8) ::     av_p_v(-2:ni+3, -2:nj+3, -2:nk+3)
  real(8) ::    au_sw_v(-2:ni+3, -2:nj+3, -2:nk+3)
  real(8) ::    au_nw_v(-2:ni+3, -2:nj+3, -2:nk+3)
  real(8) ::    au_se_v(-2:ni+3, -2:nj+3, -2:nk+3)
  real(8) ::    au_ne_v(-2:ni+3, -2:nj+3, -2:nk+3)
  real(8) ::    aw_sb_v(-2:ni+3, -2:nj+3, -2:nk+3)
  real(8) ::    aw_nb_v(-2:ni+3, -2:nj+3, -2:nk+3)
  real(8) ::    aw_st_v(-2:ni+3, -2:nj+3, -2:nk+3)
  real(8) ::    aw_nt_v(-2:ni+3, -2:nj+3, -2:nk+3)
  real(8) ::     aw_w_w(-2:ni+3, -2:nj+3, -2:nk+3)
  real(8) ::     aw_e_w(-2:ni+3, -2:nj+3, -2:nk+3)
  real(8) ::     aw_s_w(-2:ni+3, -2:nj+3, -2:nk+3)
  real(8) ::     aw_n_w(-2:ni+3, -2:nj+3, -2:nk+3)
  real(8) ::     aw_b_w(-2:ni+3, -2:nj+3, -2:nk+3)
  real(8) ::     aw_t_w(-2:ni+3, -2:nj+3, -2:nk+3)
  real(8) ::     aw_p_w(-2:ni+3, -2:nj+3, -2:nk+3)
  real(8) ::    au_bw_w(-2:ni+3, -2:nj+3, -2:nk+3)
  real(8) ::    au_tw_w(-2:ni+3, -2:nj+3, -2:nk+3)
  real(8) ::    au_be_w(-2:ni+3, -2:nj+3, -2:nk+3)
  real(8) ::    au_te_w(-2:ni+3, -2:nj+3, -2:nk+3)
  real(8) ::    av_bs_w(-2:ni+3, -2:nj+3, -2:nk+3)
  real(8) ::    av_ts_w(-2:ni+3, -2:nj+3, -2:nk+3)
  real(8) ::    av_bn_w(-2:ni+3, -2:nj+3, -2:nk+3)
  real(8) ::    av_tn_w(-2:ni+3, -2:nj+3, -2:nk+3)
  real(8) :: rhol, mul


  call init_3d(ni, nj, nk, u         , 0.0d0)
  call init_3d(ni, nj, nk, v         , 0.0d0)
  call init_3d(ni, nj, nk, w         , 0.0d0)
  call init_3d(ni, nj, nk, un        , 0.0d0)
  call init_3d(ni, nj, nk, vn        , 0.0d0)
  call init_3d(ni, nj, nk, wn        , 0.0d0)
  call init_3d(ni, nj, nk, rho       , rhol )
  call init_3d(ni, nj, nk, mu        , mul  )
  call init_3d(ni, nj, nk, rhon      , rhol )
  call init_3d(ni, nj, nk, mun       , mul  )

  call init_3d(ni, nj, nk, adv_u     , 0.0d0)
  call init_3d(ni, nj, nk, adv_v     , 0.0d0)
  call init_3d(ni, nj, nk, adv_w     , 0.0d0)
  call init_3d(ni, nj, nk, adv_uo    , 0.0d0)
  call init_3d(ni, nj, nk, adv_vo    , 0.0d0)
  call init_3d(ni, nj, nk, adv_wo    , 0.0d0)

  call init_3d(ni, nj, nk, prs_u     , 0.0d0)
  call init_3d(ni, nj, nk, prs_v     , 0.0d0)
  call init_3d(ni, nj, nk, prs_w     , 0.0d0)

  call init_4d(ni, nj, nk, 6, s      , 0.0d0)
  call init_4d(ni, nj, nk, 6, tau    , 0.0d0)
  call init_3d(ni, nj, nk, vis_u     , 0.0d0)
  call init_3d(ni, nj, nk, vis_v     , 0.0d0)
  call init_3d(ni, nj, nk, vis_w     , 0.0d0)

  call init_3d(ni, nj, nk, sum_fst_u , 0.0d0)
  call init_3d(ni, nj, nk, sum_fst_v , 0.0d0)
  call init_3d(ni, nj, nk, sum_fst_w , 0.0d0)
  call init_3d(ni, nj, nk, sum_fst_un, 0.0d0)
  call init_3d(ni, nj, nk, sum_fst_vn, 0.0d0)
  call init_3d(ni, nj, nk, sum_fst_wn, 0.0d0)

  call init_3d(ni, nj, nk, src_u     , 0.0d0)
  call init_3d(ni, nj, nk, src_v     , 0.0d0)
  call init_3d(ni, nj, nk, src_w     , 0.0d0)

  call init_3d(ni, nj, nk, au_w_u    , 0.0d0)
  call init_3d(ni, nj, nk, au_e_u    , 0.0d0)
  call init_3d(ni, nj, nk, au_s_u    , 0.0d0)
  call init_3d(ni, nj, nk, au_n_u    , 0.0d0)
  call init_3d(ni, nj, nk, au_b_u    , 0.0d0)
  call init_3d(ni, nj, nk, au_t_u    , 0.0d0)
  call init_3d(ni, nj, nk, au_p_u    , 0.0d0)
  call init_3d(ni, nj, nk, av_ws_u   , 0.0d0)
  call init_3d(ni, nj, nk, av_es_u   , 0.0d0)
  call init_3d(ni, nj, nk, av_wn_u   , 0.0d0)
  call init_3d(ni, nj, nk, av_en_u   , 0.0d0)
  call init_3d(ni, nj, nk, aw_wb_u   , 0.0d0)
  call init_3d(ni, nj, nk, aw_eb_u   , 0.0d0)
  call init_3d(ni, nj, nk, aw_wt_u   , 0.0d0)
  call init_3d(ni, nj, nk, aw_et_u   , 0.0d0)
  call init_3d(ni, nj, nk, av_w_v    , 0.0d0)
  call init_3d(ni, nj, nk, av_e_v    , 0.0d0)
  call init_3d(ni, nj, nk, av_s_v    , 0.0d0)
  call init_3d(ni, nj, nk, av_n_v    , 0.0d0)
  call init_3d(ni, nj, nk, av_b_v    , 0.0d0)
  call init_3d(ni, nj, nk, av_t_v    , 0.0d0)
  call init_3d(ni, nj, nk, av_p_v    , 0.0d0)
  call init_3d(ni, nj, nk, au_sw_v   , 0.0d0)
  call init_3d(ni, nj, nk, au_nw_v   , 0.0d0)
  call init_3d(ni, nj, nk, au_se_v   , 0.0d0)
  call init_3d(ni, nj, nk, au_ne_v   , 0.0d0)
  call init_3d(ni, nj, nk, aw_sb_v   , 0.0d0)
  call init_3d(ni, nj, nk, aw_nb_v   , 0.0d0)
  call init_3d(ni, nj, nk, aw_st_v   , 0.0d0)
  call init_3d(ni, nj, nk, aw_nt_v   , 0.0d0)
  call init_3d(ni, nj, nk, aw_w_w    , 0.0d0)
  call init_3d(ni, nj, nk, aw_e_w    , 0.0d0)
  call init_3d(ni, nj, nk, aw_s_w    , 0.0d0)
  call init_3d(ni, nj, nk, aw_n_w    , 0.0d0)
  call init_3d(ni, nj, nk, aw_b_w    , 0.0d0)
  call init_3d(ni, nj, nk, aw_t_w    , 0.0d0)
  call init_3d(ni, nj, nk, aw_p_w    , 0.0d0)
  call init_3d(ni, nj, nk, au_bw_w   , 0.0d0)
  call init_3d(ni, nj, nk, au_tw_w   , 0.0d0)
  call init_3d(ni, nj, nk, au_be_w   , 0.0d0)
  call init_3d(ni, nj, nk, au_te_w   , 0.0d0)
  call init_3d(ni, nj, nk, av_bs_w   , 0.0d0)
  call init_3d(ni, nj, nk, av_ts_w   , 0.0d0)
  call init_3d(ni, nj, nk, av_bn_w   , 0.0d0)
  call init_3d(ni, nj, nk, av_tn_w   , 0.0d0)


  return
end subroutine init
